name: Build & Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}   # you already added this
  REGION: us-central1
  REPO: us-central1-docker.pkg.dev

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # ✅ Authenticate with the JSON key you stored in GCP_SA_KEY
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        install_components: docker-credential-gcr

    - name: Configure docker auth
      run: gcloud auth configure-docker $REPO --quiet

    # --- build & push dispatcher ---
    - name: Build & push dispatcher
      run: |
        docker build -t $REPO/$PROJECT_ID/assistant/dispatcher:latest -f apps/dispatcher/Dockerfile .
        docker push  $REPO/$PROJECT_ID/assistant/dispatcher:latest

    # --- build & push echo-agent ---
    - name: Build & push echo-agent
      run: |
        docker build -t $REPO/$PROJECT_ID/assistant/echo-agent:latest -f apps/echo_agent/Dockerfile .
        docker push  $REPO/$PROJECT_ID/assistant/echo-agent:latest

    # --- deploy both services ---
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy assistant-dispatcher \
          --image $REPO/$PROJECT_ID/assistant/dispatcher:latest \
          --region $REGION --platform managed --quiet
        gcloud run deploy echo-agent \
          --image $REPO/$PROJECT_ID/assistant/echo-agent:latest \
          --region $REGION --platform managed --quiet
