name: Build & Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  REPO: us-central1-docker.pkg.dev            # Artifact Registry host

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # ───────────── 1. checkout + auth ─────────────
    - uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        install_components: docker-credential-gcr   # needed for Artifact Registry

    - name: Configure Docker cred-helper
      run: gcloud auth configure-docker $REPO --quiet

    # ───────────── 2. build & push images ─────────
    - name: Build & push dispatcher image
      run: |
        docker build -t $REPO/$PROJECT_ID/assistant-images/dispatcher:latest \
                     -f apps/dispatcher/Dockerfile .
        docker push  $REPO/$PROJECT_ID/assistant-images/dispatcher:latest

    - name: Build & push echo-agent image
      run: |
        docker build -t $REPO/$PROJECT_ID/assistant-images/echo-agent:latest \
                     -f apps/echo_agent/Dockerfile .
        docker push  $REPO/$PROJECT_ID/assistant-images/echo-agent:latest

    - name: Build & push mediator image
      run: |
        docker build -t $REPO/$PROJECT_ID/assistant-images/mediator:latest \
                     -f apps/mediator/Dockerfile .
        docker push  $REPO/$PROJECT_ID/assistant-images/mediator:latest

    # ───────────── 3. deploy to Cloud Run ─────────
    - name: Deploy all services
      run: |
        gcloud run deploy assistant-dispatcher \
          --image $REPO/$PROJECT_ID/assistant-images/dispatcher:latest \
          --region $REGION --platform managed --allow-unauthenticated --quiet \
          --update-secrets "OPENAI_API_KEY=OPENAI_API_KEY:latest" \
          --service-account dispatcher-sa@$PROJECT_ID.iam.gserviceaccount.com

        gcloud run deploy echo-agent \
          --image $REPO/$PROJECT_ID/assistant-images/echo-agent:latest \
          --region $REGION --platform managed --allow-unauthenticated --quiet \
          --service-account echo-sa@$PROJECT_ID.iam.gserviceaccount.com

        gcloud run deploy mediator-agent \
          --image $REPO/$PROJECT_ID/assistant-images/mediator:latest \
          --region $REGION --platform managed --allow-unauthenticated --quiet \
          --update-secrets "OPENAI_API_KEY=OPENAI_API_KEY:latest" \
          --service-account mediator-sa@$PROJECT_ID.iam.gserviceaccount.com

